/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectofinalsistemasoperativos;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author jisaa
 */
public class PanelMemoria extends javax.swing.JPanel {

   private final GestorMemoria gestor;
  public PanelMemoria(GestorMemoria gestor) {
        this.gestor = gestor;
        setPreferredSize(new Dimension(700, 250));
        setBackground(Color.WHITE);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        List<GestorMemoria.BloqueMemoria> bloques = obtenerBloques();
        if (bloques.isEmpty()) {
            g.drawString("Sin memoria definida.", 10, 20);
            return;
        }

        int x = 20;
        int y = 60;
        int altura = 50;
        long total = gestor.getTotalBytes();
        int anchoTotal = getWidth() - 40;

        for (GestorMemoria.BloqueMemoria b : bloques) {
            int ancho = (int) ((b.tamanoBytes / (double) total) * anchoTotal);
            if (ancho < 1) ancho = 1;

            g.setColor(b.estado == GestorMemoria.EstadoBloque.LIBRE ? Color.GREEN : Color.RED);
            g.fillRect(x, y, ancho, altura);

            g.setColor(Color.BLACK);
            g.drawRect(x, y, ancho, altura);

            String texto = (b.estado == GestorMemoria.EstadoBloque.LIBRE)
                    ? "Libre (" + b.tamanoBytes + " bytes)"
      
              : "P" + b.procesoAsignado + " (" + b.tamanoBytes + " bytes)";
            g.drawString(texto, x + 5, y + 30);

            x += ancho;
        }
    }

    private List<GestorMemoria.BloqueMemoria> obtenerBloques() {
        List<GestorMemoria.BloqueMemoria> lista = new ArrayList<>();
        GestorMemoria.BloqueMemoria actual = gestor.getCabeza();
        while (actual != null) {
            lista.add(actual);
            actual = actual.derecha;
        }
        return lista;
    }

    public void actualizarVista() {
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
